WITH
	PARAMS AS (
		SELECT
			LOCALTIMESTAMP - INTERVAL '3 days' AS FROM_TS,
			LOCALTIMESTAMP AS TO_TS
	),
	BASE AS (
		SELECT
			QV.DB_ID,
			QV.USER_ID,
			QV.QUERY_ID,
			COUNT(DISTINCT QV.PLAN_ID) AS PLAN_COUNT,
			STRING_AGG(
				DISTINCT QV.PLAN_ID::TEXT,
				', '
				ORDER BY
					QV.PLAN_ID::TEXT
			) AS PLAN_IDS,
			MIN(QV.START_TIME) AS FIRST_SEEN,
			MAX(QV.END_TIME) AS LAST_SEEN,
			SUM(QV.CALLS) AS CALLS,
			SUM(QV.TOTAL_TIME) AS TOTAL_EXEC_MS,
			SUM(
				GREATEST(
					QV.TOTAL_TIME - COALESCE(QV.BLK_READ_TIME, 0) - COALESCE(QV.BLK_WRITE_TIME, 0),
					0
				)
			) AS APPROX_CPU_MS,
			SUM(
				COALESCE(QV.BLK_READ_TIME, 0) + COALESCE(QV.BLK_WRITE_TIME, 0)
			) AS IO_TIME_MS,
			SUM(QV.ROWS) AS TOTAL_ROWS,
			SUM(QV.SHARED_BLKS_HIT) AS SHARED_BLKS_HIT,
			SUM(QV.SHARED_BLKS_READ) AS SHARED_BLKS_READ,
			SUM(QV.SHARED_BLKS_DIRTIED) AS SHARED_BLKS_DIRTIED,
			SUM(QV.SHARED_BLKS_WRITTEN) AS SHARED_BLKS_WRITTEN,
			SUM(QV.TEMP_BLKS_READ) AS TEMP_BLKS_READ,
			SUM(QV.TEMP_BLKS_WRITTEN) AS TEMP_BLKS_WRITTEN,
			MIN(QV.MIN_TIME) AS MIN_EXEC_MS,
			MAX(QV.MAX_TIME) AS MAX_EXEC_MS,
			MAX(QV.QUERY_TYPE) AS QUERY_TYPE,
			REGEXP_REPLACE(MAX(QV.QUERY_SQL_TEXT), '\s+', ' ', 'g') AS QUERY_TEXT
		FROM
			QUERY_STORE.QS_VIEW QV
			CROSS JOIN PARAMS P
		WHERE
			QV.END_TIME > P.FROM_TS
			AND QV.START_TIME < P.TO_TS
			AND QV.IS_SYSTEM_QUERY IS FALSE
		GROUP BY
			QV.DB_ID,
			QV.USER_ID,
			QV.QUERY_ID
	),
	TOTALS AS (
		SELECT
			SUM(TOTAL_EXEC_MS) AS WORKLOAD_EXEC_MS,
			SUM(APPROX_CPU_MS) AS WORKLOAD_APPROX_CPU_MS
		FROM
			BASE
	)
SELECT
	COALESCE(D.DATNAME, B.DB_ID::TEXT) AS DATABASE_NAME,
	COALESCE(R.ROLNAME, B.USER_ID::TEXT) AS USER_NAME,
	B.QUERY_ID,
	B.QUERY_TYPE,
	B.PLAN_COUNT,
	B.PLAN_IDS,
	B.FIRST_SEEN,
	B.LAST_SEEN,
	B.CALLS,
	ROUND((B.TOTAL_EXEC_MS / 1000.0)::NUMERIC, 2) AS TOTAL_EXEC_SEC,
	ROUND(
		(
			100.0 * B.TOTAL_EXEC_MS / NULLIF(T.WORKLOAD_EXEC_MS, 0)
		)::NUMERIC,
		2
	) AS EXEC_TIME_PCT_OF_WORKLOAD,
	ROUND((B.APPROX_CPU_MS / 1000.0)::NUMERIC, 2) AS APPROX_CPU_SEC,
	ROUND(
		(
			100.0 * B.APPROX_CPU_MS / NULLIF(T.WORKLOAD_APPROX_CPU_MS, 0)
		)::NUMERIC,
		2
	) AS APPROX_CPU_PCT_OF_WORKLOAD,
	ROUND((B.IO_TIME_MS / 1000.0)::NUMERIC, 2) AS IO_TIME_SEC,
	ROUND(
		(100.0 * B.IO_TIME_MS / NULLIF(B.TOTAL_EXEC_MS, 0))::NUMERIC,
		2
	) AS IO_TIME_PCT_INSIDE_QUERY,
	ROUND(
		(B.TOTAL_EXEC_MS / NULLIF(B.CALLS, 0))::NUMERIC,
		2
	) AS AVG_EXEC_MS_PER_CALL,
	ROUND(B.MIN_EXEC_MS::NUMERIC, 2) AS MIN_EXEC_MS,
	ROUND(B.MAX_EXEC_MS::NUMERIC, 2) AS MAX_EXEC_MS,
	ROUND((B.TOTAL_ROWS::NUMERIC / NULLIF(B.CALLS, 0)), 2) AS AVG_ROWS_PER_CALL,
	B.SHARED_BLKS_HIT,
	B.SHARED_BLKS_READ,
	B.SHARED_BLKS_DIRTIED,
	B.SHARED_BLKS_WRITTEN,
	B.TEMP_BLKS_READ,
	B.TEMP_BLKS_WRITTEN,
	LEFT(B.QUERY_TEXT, 3000) AS QUERY_TEXT
FROM
	BASE B
	CROSS JOIN TOTALS T
	LEFT JOIN PG_DATABASE D ON D.OID = B.DB_ID
	LEFT JOIN PG_ROLES R ON R.OID = B.USER_ID
ORDER BY
	B.APPROX_CPU_MS DESC
LIMIT
	50;
